services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: Qribly-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: qribly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qribly

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qribly"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: Qribly-backend
    restart: unless-stopped
    

    working_dir: /var/www

    volumes:
      - ./backend:/var/www

    ports:
      - "8000:8000"

    environment:
      APP_ROLE: backend


    command: php artisan serve --host=0.0.0.0 --port=8000

    depends_on:
      postgres:
        condition: service_healthy

  reverb:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: Qribly-reverb
    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - ./backend:/var/www

    ports:
      - "8080:8080"
    
    environment:
      APP_ROLE: reverb


    command: php artisan reverb:start --host=0.0.0.0 --port=8080

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: Qribly-frontend
    restart: unless-stopped

    working_dir: /app

    volumes:
      - ./frontend:/app
      - /app/node_modules

    ports:
      - "5173:5173"

    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: http://localhost:8000/api
      VITE_REVERB_APP_KEY: qribly-local-key
      VITE_REVERB_HOST: localhost
      VITE_REVERB_PORT: 8080
      VITE_REVERB_SCHEME: http
      

    depends_on:
      - backend

    command: npm run dev -- --host

volumes:
  postgres_data: