FROM node:22-alpine AS frontend-build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ ./

ENV VITE_API_URL=/api

RUN npm run build


FROM nginx:alpine

COPY --from=frontend-build /app/dist /usr/share/nginx/html

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf