<?php

namespace Database\Seeders;

final class DemoCatalog
{
    public const PASSWORD = 'password';

    /** @var array<string, string> */
    public const CATEGORIES = [
        'Restaurants' => 'Restauration',
        'Electronics' => 'Électronique',
        'Clothing' => 'Mode',
        'Home Services' => 'Services à domicile',
        'Transportation' => 'Transport',
        'Education' => 'Éducation',
        'Beauty' => 'Beauté',
        'Groceries' => 'Alimentation',
    ];

    /** @var array<int, array{name: string, email: string}> */
    public const USERS = [
        ['name' => 'Nadia El Mansouri', 'email' => 'prestataire@qribly.test'],
        ['name' => 'Youssef Amrani', 'email' => 'youssef@qribly.test'],
        ['name' => 'Sara Benali', 'email' => 'sara@qribly.test'],
        ['name' => 'Omar Alaoui', 'email' => 'omar@qribly.test'],
        ['name' => 'Salma Idrissi', 'email' => 'salma@qribly.test'],
        ['name' => 'Mehdi Berrada', 'email' => 'client@qribly.test'],
        ['name' => 'Lina Tahiri', 'email' => 'lina@qribly.test'],
    ];

    /**
     * @var array<int, array{
     *     slug: string,
     *     user: string,
     *     category: string,
     *     title: string,
     *     description: string,
     *     type: 'product'|'service',
     *     price: int,
     *     is_negotiable: bool,
     *     status: 'active'|'reserved'|'sold'|'inactive',
     *     city: string,
     *     duration: int|null,
     *     at_customer_location?: bool,
     *     at_provider_location?: bool,
     *     latitude: float,
     *     longitude: float
     * }>
     */
    public const OFFERS = [
        [
            'slug' => 'grand-menage-appartement',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Grand ménage d’un appartement',
            'description' => 'Un nettoyage complet de votre appartement : cuisine, sanitaires, sols, poussière et surfaces. Le matériel et les produits courants sont inclus. Idéal avant un emménagement, après un départ ou pour un grand ménage saisonnier.',
            'type' => 'service',
            'price' => 250,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 120,
            'latitude' => 31.6328,
            'longitude' => -8.0104,
        ],
        [
            'slug' => 'entretien-climatisation',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Entretien et nettoyage de climatisation',
            'description' => 'Entretien préventif d’une unité de climatisation avec nettoyage des filtres, contrôle de l’évacuation et vérification du bon fonctionnement. Un diagnostic clair est fourni avant toute réparation supplémentaire.',
            'type' => 'service',
            'price' => 300,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 90,
            'latitude' => 31.6604,
            'longitude' => -8.0031,
        ],
        [
            'slug' => 'reparation-smartphone',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'Réparation de smartphone',
            'description' => 'Diagnostic et réparation de smartphone pour les problèmes d’écran, de batterie, de charge ou de logiciel. Le prix indiqué correspond au diagnostic et à la main-d’œuvre de base ; les pièces sont proposées séparément.',
            'type' => 'service',
            'price' => 180,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 60,
            'at_customer_location' => false,
            'at_provider_location' => true,
            'latitude' => 33.5896,
            'longitude' => -7.6201,
        ],
        [
            'slug' => 'pc-portable-reconditionne',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'PC portable reconditionné',
            'description' => 'Ordinateur portable reconditionné, soigneusement testé et prêt à l’emploi. Il convient aux études, à la bureautique et aux visioconférences. Chargeur compatible fourni et essai possible sur place.',
            'type' => 'product',
            'price' => 3900,
            'is_negotiable' => true,
            'status' => 'reserved',
            'city' => 'Casablanca',
            'duration' => null,
            'latitude' => 33.5731,
            'longitude' => -7.5898,
        ],
        [
            'slug' => 'cours-mathematiques',
            'user' => 'omar@qribly.test',
            'category' => 'Éducation',
            'title' => 'Cours de soutien en mathématiques',
            'description' => 'Séance individuelle de soutien en mathématiques pour le collège et le lycée. Nous reprenons les notions difficiles, les exercices du cours et une méthode de travail adaptée au niveau de l’élève.',
            'type' => 'service',
            'price' => 150,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 90,
            'latitude' => 34.0151,
            'longitude' => -6.8326,
        ],
        [
            'slug' => 'coiffure-brushing-domicile',
            'user' => 'salma@qribly.test',
            'category' => 'Beauté',
            'title' => 'Coiffure et brushing à domicile',
            'description' => 'Coiffure à domicile avec brushing adapté à la nature de vos cheveux. Le service comprend un échange avant le rendez-vous pour préparer le style souhaité. Les prestations événementielles peuvent être ajoutées sur demande.',
            'type' => 'service',
            'price' => 200,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 60,
            'at_customer_location' => true,
            'at_provider_location' => false,
            'latitude' => 34.0242,
            'longitude' => -6.8467,
        ],
        [
            'slug' => 'livraison-petits-colis',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Livraison express de petits colis',
            'description' => 'Collecte et livraison de petits colis dans Marrakech et les quartiers proches. Le suivi se fait directement par message. Le tarif couvre une course urbaine standard, avec confirmation avant départ.',
            'type' => 'service',
            'price' => 50,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 60,
            'latitude' => 31.6257,
            'longitude' => -7.9892,
        ],
        [
            'slug' => 'location-vtt-ourika',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Location de VTT dans la vallée de l’Ourika',
            'description' => 'Location d’un VTT entretenu avec casque, kit de réparation et conseils d’itinéraire. Une prise en main rapide est prévue avant le départ. Convient aux sorties de niveau débutant à intermédiaire.',
            'type' => 'service',
            'price' => 180,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Ourika',
            'duration' => 240,
            'latitude' => 31.3742,
            'longitude' => -7.7778,
        ],
        [
            'slug' => 'chef-domicile-menu-marocain',
            'user' => 'prestataire@qribly.test',
            'category' => 'Restauration',
            'title' => 'Chef à domicile — menu marocain',
            'description' => 'Préparation à domicile d’un menu marocain généreux pour un repas en famille ou entre amis. Le menu est défini à l’avance selon vos préférences et allergies. Les ingrédients sont facturés séparément sur justificatif.',
            'type' => 'service',
            'price' => 600,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Agadir',
            'duration' => 180,
            'latitude' => 30.4202,
            'longitude' => -9.5988,
        ],
        [
            'slug' => 'panier-legumes-bio',
            'user' => 'youssef@qribly.test',
            'category' => 'Alimentation',
            'title' => 'Panier de légumes bio de saison',
            'description' => 'Panier varié de légumes frais provenant de petits producteurs de la région. La composition change selon la récolte et permet de préparer les repas d’une famille pendant plusieurs jours.',
            'type' => 'product',
            'price' => 120,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => null,
            'latitude' => 31.7001,
            'longitude' => -8.0302,
        ],
        [
            'slug' => 'caftan-marocain-brode',
            'user' => 'salma@qribly.test',
            'category' => 'Mode',
            'title' => 'Caftan marocain brodé à la main',
            'description' => 'Caftan marocain confectionné avec soin, broderies réalisées à la main et finitions traditionnelles. La pièce a été portée une seule fois et peut être essayée sur rendez-vous.',
            'type' => 'product',
            'price' => 1450,
            'is_negotiable' => true,
            'status' => 'sold',
            'city' => 'Tanger',
            'duration' => null,
            'latitude' => 35.7684,
            'longitude' => -5.8187,
        ],
        [
            'slug' => 'patisseries-marocaines',
            'user' => 'salma@qribly.test',
            'category' => 'Restauration',
            'title' => 'Assortiment de pâtisseries marocaines',
            'description' => 'Assortiment préparé sur commande avec cornes de gazelle, ghriba et briouates aux amandes. La boîte est adaptée aux réceptions, aux cadeaux et aux pauses gourmandes.',
            'type' => 'product',
            'price' => 160,
            'is_negotiable' => false,
            'status' => 'inactive',
            'city' => 'Essaouira',
            'duration' => null,
            'latitude' => 31.5132,
            'longitude' => -9.7694,
        ],
    ];

    /**
     * Offres de démonstration sans photos, dédiées aux tests de recherche et
     * de compatibilité des demandes de service.
     *
     * @var array<int, array{
     *     slug: string,
     *     user: string,
     *     category: string,
     *     title: string,
     *     description: string,
     *     type: 'service',
     *     price: int,
     *     is_negotiable: bool,
     *     status: 'active',
     *     city: string,
     *     duration: int,
     *     at_customer_location?: bool,
     *     at_provider_location?: bool,
     *     latitude: float,
     *     longitude: float
     * }>
     */
    public const TEXT_ONLY_OFFERS = [
        [
            'slug' => 'depannage-plomberie-rabat',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Dépannage plomberie à domicile',
            'description' => 'Intervention à Rabat pour une fuite d’eau, un robinet qui coule, un siphon bouché ou une petite réparation de plomberie. Le diagnostic et le déplacement à domicile sont inclus dans le tarif de base.',
            'type' => 'service',
            'price' => 220,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 90,
            'at_customer_location' => true,
            'at_provider_location' => false,
            'latitude' => 34.0209,
            'longitude' => -6.8416,
        ],
        [
            'slug' => 'grand-menage-casablanca',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Grand ménage à Casablanca',
            'description' => 'Nettoyage approfondi d’un appartement ou d’une maison à Casablanca : cuisine, sanitaires, vitres accessibles, sols et dépoussiérage. Convient particulièrement après un déménagement ou avant une réception.',
            'type' => 'service',
            'price' => 320,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 180,
            'latitude' => 33.5899,
            'longitude' => -7.6186,
        ],
        [
            'slug' => 'nettoyage-maison-fes',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Nettoyage complet de maison à Fès',
            'description' => 'Prestation de ménage à domicile à Fès pour nettoyer les pièces de vie, la cuisine, les salles de bain et les sols. Le contenu exact est confirmé avec le client avant l’intervention.',
            'type' => 'service',
            'price' => 280,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Fès',
            'duration' => 180,
            'latitude' => 34.0347,
            'longitude' => -5.0000,
        ],
        [
            'slug' => 'depannage-electricite-marrakech',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Dépannage électrique à Marrakech',
            'description' => 'Recherche de panne électrique, remplacement d’une prise ou d’un interrupteur et réparation de petits problèmes d’installation à domicile à Marrakech. Un devis est annoncé avant les travaux supplémentaires.',
            'type' => 'service',
            'price' => 280,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 120,
            'latitude' => 31.6352,
            'longitude' => -8.0041,
        ],
        [
            'slug' => 'reparation-velo-marrakech',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Réparation et réglage de vélo',
            'description' => 'Réparation de vélo à Marrakech : crevaison, freins, vitesses, chaîne et réglages de sécurité. Le vélo est vérifié avant restitution et les pièces éventuelles sont annoncées séparément.',
            'type' => 'service',
            'price' => 140,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 90,
            'at_customer_location' => false,
            'at_provider_location' => true,
            'latitude' => 31.6298,
            'longitude' => -7.9954,
        ],
        [
            'slug' => 'reparation-velo-casablanca',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Atelier mobile de réparation vélo',
            'description' => 'Entretien et réparation de vélos à Casablanca avec intervention possible à domicile. Diagnostic des freins, pneus, transmission et roues avant de proposer le prix final.',
            'type' => 'service',
            'price' => 160,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 90,
            'latitude' => 33.5781,
            'longitude' => -7.6306,
        ],
        [
            'slug' => 'chauffeur-prive-fes',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Chauffeur privé pour trajet local',
            'description' => 'Service de chauffeur à Fès pour un déplacement en ville, un rendez-vous ou un transfert vers la gare ou l’aéroport. L’horaire et le point de prise en charge sont confirmés à l’avance.',
            'type' => 'service',
            'price' => 300,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Fès',
            'duration' => 180,
            'latitude' => 34.0415,
            'longitude' => -4.9975,
        ],
        [
            'slug' => 'livraison-courses-rabat',
            'user' => 'youssef@qribly.test',
            'category' => 'Alimentation',
            'title' => 'Courses et livraison à domicile',
            'description' => 'Achat et livraison de courses alimentaires à Rabat à partir d’une liste fournie par le client. Les produits sont payés sur justificatif et le tarif correspond au service de collecte et de livraison.',
            'type' => 'service',
            'price' => 70,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 60,
            'latitude' => 34.0117,
            'longitude' => -6.8361,
        ],
        [
            'slug' => 'cours-anglais-rabat',
            'user' => 'omar@qribly.test',
            'category' => 'Éducation',
            'title' => 'Cours d’anglais conversationnel',
            'description' => 'Cours individuel d’anglais à Rabat pour améliorer l’expression orale, le vocabulaire et la confiance en conversation. La séance est adaptée au niveau débutant ou intermédiaire.',
            'type' => 'service',
            'price' => 130,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 60,
            'latitude' => 34.0164,
            'longitude' => -6.8292,
        ],
        [
            'slug' => 'cours-francais-casablanca',
            'user' => 'omar@qribly.test',
            'category' => 'Éducation',
            'title' => 'Soutien scolaire en français',
            'description' => 'Accompagnement en français à Casablanca pour le collège : grammaire, rédaction, compréhension de texte et préparation des contrôles. Un bilan rapide permet de cibler les difficultés prioritaires.',
            'type' => 'service',
            'price' => 140,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 90,
            'latitude' => 33.5735,
            'longitude' => -7.6102,
        ],
        [
            'slug' => 'initiation-informatique-fes',
            'user' => 'omar@qribly.test',
            'category' => 'Éducation',
            'title' => 'Initiation à l’informatique',
            'description' => 'Cours pratique à Fès pour apprendre à utiliser un ordinateur, organiser ses fichiers, naviguer sur Internet et utiliser les outils bureautiques essentiels. Le rythme est adapté aux débutants.',
            'type' => 'service',
            'price' => 170,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Fès',
            'duration' => 90,
            'latitude' => 34.0292,
            'longitude' => -5.0073,
        ],
        [
            'slug' => 'reparation-pc-casablanca',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'Réparation d’ordinateur portable',
            'description' => 'Diagnostic et dépannage de PC portable à Casablanca pour les problèmes de démarrage, lenteur, surchauffe, batterie ou logiciel. Les données du client ne sont jamais effacées sans son accord.',
            'type' => 'service',
            'price' => 250,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 120,
            'latitude' => 33.5845,
            'longitude' => -7.6037,
        ],
        [
            'slug' => 'depannage-informatique-marrakech',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'Dépannage informatique à domicile',
            'description' => 'Assistance informatique à Marrakech pour installer un logiciel, supprimer un virus, configurer une imprimante ou résoudre un problème de connexion. Intervention sur ordinateur Windows à domicile.',
            'type' => 'service',
            'price' => 200,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 90,
            'latitude' => 31.6417,
            'longitude' => -8.0128,
        ],
        [
            'slug' => 'reparation-smartphone-fes',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'Diagnostic et réparation de smartphone',
            'description' => 'Diagnostic d’un téléphone à Fès en cas d’écran cassé, batterie faible, problème de charge ou panne logicielle. Le devis des pièces est présenté avant toute réparation.',
            'type' => 'service',
            'price' => 190,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Fès',
            'duration' => 60,
            'latitude' => 34.0364,
            'longitude' => -5.0046,
        ],
        [
            'slug' => 'maquillage-evenementiel-rabat',
            'user' => 'salma@qribly.test',
            'category' => 'Beauté',
            'title' => 'Maquillage événementiel à domicile',
            'description' => 'Maquillage à domicile à Rabat pour mariage, fiançailles, cérémonie ou séance photo. Le style, les couleurs et le niveau de couvrance sont définis avec la cliente avant la prestation.',
            'type' => 'service',
            'price' => 350,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 90,
            'latitude' => 34.0249,
            'longitude' => -6.8393,
        ],
        [
            'slug' => 'maquillage-marrakech',
            'user' => 'salma@qribly.test',
            'category' => 'Beauté',
            'title' => 'Maquillage soirée à Marrakech',
            'description' => 'Prestation de maquillage pour une soirée ou un événement à Marrakech, avec préparation de la peau et choix d’un rendu naturel ou plus soutenu. Déplacement à domicile possible.',
            'type' => 'service',
            'price' => 300,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 75,
            'latitude' => 31.6225,
            'longitude' => -8.0087,
        ],
        [
            'slug' => 'retouches-couture-fes',
            'user' => 'salma@qribly.test',
            'category' => 'Mode',
            'title' => 'Retouches et réparations de vêtements',
            'description' => 'Service de couture à Fès pour raccourcir un pantalon, ajuster une robe, remplacer une fermeture ou réparer un vêtement. Le délai et le prix sont confirmés après examen de la pièce.',
            'type' => 'service',
            'price' => 120,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Fès',
            'duration' => 60,
            'latitude' => 34.0438,
            'longitude' => -5.0101,
        ],
        [
            'slug' => 'traiteur-buffet-casablanca',
            'user' => 'prestataire@qribly.test',
            'category' => 'Restauration',
            'title' => 'Traiteur pour buffet marocain',
            'description' => 'Préparation d’un buffet marocain à Casablanca pour une réception familiale ou professionnelle. Le menu, le nombre de personnes, les allergies et les modalités de livraison sont définis avant validation.',
            'type' => 'service',
            'price' => 700,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 240,
            'latitude' => 33.5943,
            'longitude' => -7.6271,
        ],
    ];

    /** @return array<int, array<string, mixed>> */
    public static function allOffers(): array
    {
        return [...self::OFFERS, ...self::TEXT_ONLY_OFFERS];
    }

    /** @return array<int, string> */
    public static function offerSlugs(): array
    {
        return array_column(self::allOffers(), 'slug');
    }
}
