<?php

namespace Database\Seeders;

final class DemoCatalog
{
    public const PASSWORD = 'password';

    /** @var array<string, string> */
    public const CATEGORIES = [
        'Restaurants' => 'Restauration',
        'Electronics' => 'Électronique',
        'Clothing' => 'Mode',
        'Home Services' => 'Services à domicile',
        'Transportation' => 'Transport',
        'Education' => 'Éducation',
        'Beauty' => 'Beauté',
        'Groceries' => 'Alimentation',
    ];

    /** @var array<int, array{name: string, email: string}> */
    public const USERS = [
        ['name' => 'Nadia El Mansouri', 'email' => 'prestataire@qribly.test'],
        ['name' => 'Youssef Amrani', 'email' => 'youssef@qribly.test'],
        ['name' => 'Sara Benali', 'email' => 'sara@qribly.test'],
        ['name' => 'Omar Alaoui', 'email' => 'omar@qribly.test'],
        ['name' => 'Salma Idrissi', 'email' => 'salma@qribly.test'],
        ['name' => 'Mehdi Berrada', 'email' => 'client@qribly.test'],
        ['name' => 'Lina Tahiri', 'email' => 'lina@qribly.test'],
    ];

    /**
     * @var array<int, array{
     *     slug: string,
     *     user: string,
     *     category: string,
     *     title: string,
     *     description: string,
     *     type: 'product'|'service',
     *     price: int,
     *     is_negotiable: bool,
     *     status: 'active'|'reserved'|'sold'|'inactive',
     *     city: string,
     *     duration: int|null,
     *     latitude: float,
     *     longitude: float
     * }>
     */
    public const OFFERS = [
        [
            'slug' => 'grand-menage-appartement',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Grand ménage d’un appartement',
            'description' => 'Un nettoyage complet de votre appartement : cuisine, sanitaires, sols, poussière et surfaces. Le matériel et les produits courants sont inclus. Idéal avant un emménagement, après un départ ou pour un grand ménage saisonnier.',
            'type' => 'service',
            'price' => 250,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 120,
            'latitude' => 31.6328,
            'longitude' => -8.0104,
        ],
        [
            'slug' => 'entretien-climatisation',
            'user' => 'prestataire@qribly.test',
            'category' => 'Services à domicile',
            'title' => 'Entretien et nettoyage de climatisation',
            'description' => 'Entretien préventif d’une unité de climatisation avec nettoyage des filtres, contrôle de l’évacuation et vérification du bon fonctionnement. Un diagnostic clair est fourni avant toute réparation supplémentaire.',
            'type' => 'service',
            'price' => 300,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 90,
            'latitude' => 31.6604,
            'longitude' => -8.0031,
        ],
        [
            'slug' => 'reparation-smartphone',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'Réparation de smartphone',
            'description' => 'Diagnostic et réparation de smartphone pour les problèmes d’écran, de batterie, de charge ou de logiciel. Le prix indiqué correspond au diagnostic et à la main-d’œuvre de base ; les pièces sont proposées séparément.',
            'type' => 'service',
            'price' => 180,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Casablanca',
            'duration' => 60,
            'latitude' => 33.5896,
            'longitude' => -7.6201,
        ],
        [
            'slug' => 'pc-portable-reconditionne',
            'user' => 'sara@qribly.test',
            'category' => 'Électronique',
            'title' => 'PC portable reconditionné',
            'description' => 'Ordinateur portable reconditionné, soigneusement testé et prêt à l’emploi. Il convient aux études, à la bureautique et aux visioconférences. Chargeur compatible fourni et essai possible sur place.',
            'type' => 'product',
            'price' => 3900,
            'is_negotiable' => true,
            'status' => 'reserved',
            'city' => 'Casablanca',
            'duration' => null,
            'latitude' => 33.5731,
            'longitude' => -7.5898,
        ],
        [
            'slug' => 'cours-mathematiques',
            'user' => 'omar@qribly.test',
            'category' => 'Éducation',
            'title' => 'Cours de soutien en mathématiques',
            'description' => 'Séance individuelle de soutien en mathématiques pour le collège et le lycée. Nous reprenons les notions difficiles, les exercices du cours et une méthode de travail adaptée au niveau de l’élève.',
            'type' => 'service',
            'price' => 150,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 90,
            'latitude' => 34.0151,
            'longitude' => -6.8326,
        ],
        [
            'slug' => 'coiffure-brushing-domicile',
            'user' => 'salma@qribly.test',
            'category' => 'Beauté',
            'title' => 'Coiffure et brushing à domicile',
            'description' => 'Coiffure à domicile avec brushing adapté à la nature de vos cheveux. Le service comprend un échange avant le rendez-vous pour préparer le style souhaité. Les prestations événementielles peuvent être ajoutées sur demande.',
            'type' => 'service',
            'price' => 200,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Rabat',
            'duration' => 60,
            'latitude' => 34.0242,
            'longitude' => -6.8467,
        ],
        [
            'slug' => 'livraison-petits-colis',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Livraison express de petits colis',
            'description' => 'Collecte et livraison de petits colis dans Marrakech et les quartiers proches. Le suivi se fait directement par message. Le tarif couvre une course urbaine standard, avec confirmation avant départ.',
            'type' => 'service',
            'price' => 50,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => 60,
            'latitude' => 31.6257,
            'longitude' => -7.9892,
        ],
        [
            'slug' => 'location-vtt-ourika',
            'user' => 'youssef@qribly.test',
            'category' => 'Transport',
            'title' => 'Location de VTT dans la vallée de l’Ourika',
            'description' => 'Location d’un VTT entretenu avec casque, kit de réparation et conseils d’itinéraire. Une prise en main rapide est prévue avant le départ. Convient aux sorties de niveau débutant à intermédiaire.',
            'type' => 'service',
            'price' => 180,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Ourika',
            'duration' => 240,
            'latitude' => 31.3742,
            'longitude' => -7.7778,
        ],
        [
            'slug' => 'chef-domicile-menu-marocain',
            'user' => 'prestataire@qribly.test',
            'category' => 'Restauration',
            'title' => 'Chef à domicile — menu marocain',
            'description' => 'Préparation à domicile d’un menu marocain généreux pour un repas en famille ou entre amis. Le menu est défini à l’avance selon vos préférences et allergies. Les ingrédients sont facturés séparément sur justificatif.',
            'type' => 'service',
            'price' => 600,
            'is_negotiable' => true,
            'status' => 'active',
            'city' => 'Agadir',
            'duration' => 180,
            'latitude' => 30.4202,
            'longitude' => -9.5988,
        ],
        [
            'slug' => 'panier-legumes-bio',
            'user' => 'youssef@qribly.test',
            'category' => 'Alimentation',
            'title' => 'Panier de légumes bio de saison',
            'description' => 'Panier varié de légumes frais provenant de petits producteurs de la région. La composition change selon la récolte et permet de préparer les repas d’une famille pendant plusieurs jours.',
            'type' => 'product',
            'price' => 120,
            'is_negotiable' => false,
            'status' => 'active',
            'city' => 'Marrakech',
            'duration' => null,
            'latitude' => 31.7001,
            'longitude' => -8.0302,
        ],
        [
            'slug' => 'caftan-marocain-brode',
            'user' => 'salma@qribly.test',
            'category' => 'Mode',
            'title' => 'Caftan marocain brodé à la main',
            'description' => 'Caftan marocain confectionné avec soin, broderies réalisées à la main et finitions traditionnelles. La pièce a été portée une seule fois et peut être essayée sur rendez-vous.',
            'type' => 'product',
            'price' => 1450,
            'is_negotiable' => true,
            'status' => 'sold',
            'city' => 'Tanger',
            'duration' => null,
            'latitude' => 35.7684,
            'longitude' => -5.8187,
        ],
        [
            'slug' => 'patisseries-marocaines',
            'user' => 'salma@qribly.test',
            'category' => 'Restauration',
            'title' => 'Assortiment de pâtisseries marocaines',
            'description' => 'Assortiment préparé sur commande avec cornes de gazelle, ghriba et briouates aux amandes. La boîte est adaptée aux réceptions, aux cadeaux et aux pauses gourmandes.',
            'type' => 'product',
            'price' => 160,
            'is_negotiable' => false,
            'status' => 'inactive',
            'city' => 'Essaouira',
            'duration' => null,
            'latitude' => 31.5132,
            'longitude' => -9.7694,
        ],
    ];

    /** @return array<int, string> */
    public static function offerSlugs(): array
    {
        return array_column(self::OFFERS, 'slug');
    }
}
